import { createClient } from '@supabase/supabase-js'
import { SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY } from './env.js'

// Use validated environment variables exported from src/config/env.ts

// Create Supabase client for client-side operations
export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)

// Create Supabase client for server-side operations (with service role)
export const supabaseAdmin = SUPABASE_SERVICE_ROLE_KEY
  ? createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)
  : null

// Database types (generated from Supabase)
export type Database = {
  // This will be generated by Supabase CLI
  // Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts
}
